export default {
	// Popular Products Constants
	GET_POPULAR_PRODUCTS: 'GET_POPULAR_PRODUCTS',
	GET_POPULAR_PRODUCTS_BY_DEMOGRAPHIC: ' GET_POPULAR_PRODUCTS_BY_DEMOGRAPHIC',
	GET_POPULAR_PRODUCTS_BY_TYPE: 'GET_POPULAR_PRODUCTS_BY_TYPE',
	GET_POPULAR_PRODUCTS_BY_CATEGORY: 'GET_POPULAR_PRODUCTS_BY_CATEGORY',
	GET_POPULAR_PRODUCTS_BY_DEMO_AND_TYPE: 'GET_POPULAR_PRODUCTS_BY_DEMO_AND_TYPE',
	GET_POPULAR_PRODUCTS_BY_DEMO_AND_CATEGORY: 'GET_POPULAR_PRODUCTS_BY_DEMO_AND_CATEGORY',
	GET_POPULAR_PRODUCTS_SAGA: 'GET_POPULAR_PRODUCTS_SAGA',
	GET_POPULAR_PRODUCTS_BY_DEMOGRAPHIC_SAGA: ' GET_POPULAR_PRODUCTS_BY_DEMOGRAPHIC_SAGA',
	GET_POPULAR_PRODUCTS_BY_TYPE_SAGA: 'GET_POPULAR_PRODUCTS_BY_TYPE_SAGA',
	GET_POPULAR_PRODUCTS_BY_CATEGORY_SAGA: ' GET_POPULAR_PRODUCTS_BY_CATEGORY_SAGA',
	
	// All Products Constants
	GET_ALL_PRODUCTS_BY_DEMOGRAPHIC_SAGA: 'GET_ALL_PRODUCTS_BY_DEMOGRAPHIC_SAGA',
	GET_ALL_PRODUCTS_BY_DEMOGRAPHIC: 'GET_ALL_PRODUCTS_BY_DEMOGRAPHIC',
	GET_ALL_PRODUCTS_BY_DEMOGRAPHIC_AND_TYPE_SAGA: 'GET_ALL_PRODUCTS_BY_DEMOGRAPHIC_AND_TYPE_SAGA',
	GET_ALL_PRODUCTS_BY_DEMOGRAPHIC_AND_TYPE: 'GET_ALL_PRODUCTS_BY_DEMOGRAPHIC_AND_TYPE',
	GET_ALL_PRODUCTS_BY_DEMOGRAPHIC_AND_CATEGORY_SAGA: 'GET_ALL_PRODUCTS_BY_DEMOGRAPHIC_AND_CATEGORY_SAGA',
	GET_ALL_PRODUCTS_BY_DEMOGRAPHIC_AND_CATEGORY: 'GET_ALL_PRODUCTS_BY_DEMOGRAPHIC_AND_CATEGORY',
	GET_POPULAR_PRODUCTS_BY_DEMO_AND_TYPE_SAGA: 'GET_POPULAR_PRODUCTS_BY_DEMO_AND_TYPE_SAGA',
	GET_POPULAR_PRODUCTS_BY_DEMO_AND_CATEGORY_SAGA: 'GET_POPULAR_PRODUCTS_BY_DEMO_AND_CATEGORY_SAGA',
	HANDLE_ERROR: 'HANDLE_ERROR',

	// New Products Constants
	GET_NEW_PRODUCTS: 'GET_NEW_PRODUCTS',
	GET_DATA: 'GET_DATA',
	GET_RESPONSE: 'GET_RESPONSE',
	GET_NEW_PRODUCTS_DEMOGRAPHIC: 'GET_NEW_PRODUCTS_DEMOGRAPHIC',
	GET_NEW_PRODUCTS_DEMOGRAPHIC_DATA: 'GET_NEW_PRODUCTS_DEMOGRAPHIC_DATA',
	GET_NEW_PRODUCTS_DEMOGRAPHIC_TYPE: 'GET_NEW_PRODUCTS_DEMOGRAPHIC_TYPE',
	GET_NEW_PRODUCTS_DEMOGRAPHIC_TYPE_DATA: 'GET_NEW_PRODUCTS_DEMOGRAPHIC_TYPE_DATA',
	GET_NEW_PRODUCTS_CATEGORY: 'GET_NEW_PRODUCTS_CATEGORY',
	GET_NEW_PRODUCTS_CATEGORY_DATA: 'GET_NEW_PRODUCTS_CATEGORY_DATA'
	


};